In [1]:
! pip install pandas

Requirement already satisfied: pandas in C:\Program Files\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Program Files\Python313\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Program Files\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Program Files\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Program Files\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.3'

In [4]:
# Dataframe

In [3]:
df = pd.DataFrame([11,22,33] , columns= ['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
data = {
    'Name' : ['Mosh','Alex','Lily','Eren'] ,
    'Age'  : [21,15,17,22] ,
    'Salary' : [50000,30000,20000,60000],
}

In [5]:
df = pd.DataFrame(data)
print(df)

   Name  Age  Salary
0  Mosh   21   50000
1  Alex   15   30000
2  Lily   17   20000
3  Eren   22   60000

In [20]:
df.head() # only returns few rows by default 5 rows get printed

   Name  Age  Salary
0  Mosh   21   50000
1  Alex   15   30000
2  Lily   17   20000
3  Eren   22   60000

In [23]:
df.tail(2)  # Return bottom rows

   Name  Age  Salary
2  Lily   17   20000
3  Eren   22   60000

In [27]:
df.shape # For finding how many (rows,columns) are available in the table

(4, 3)

In [28]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [6]:
df.rename(columns={'Name' : 'Employee'} , inplace=True) # IF we dont use inplace the column is renamed only for that particular cell using inplace we change it globally 
# or we can also use a variable to store it df1 = df

In [39]:
df

  Employee  Age  Salary
0     Mosh   21   50000
1     Alex   15   30000
2     Lily   17   20000
3     Eren   22   60000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Employee  4 non-null      object
 1   Age       4 non-null      int64
 2   Salary    4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [52]:
df.describe().round(2)   #describe is used to calculate basic aggreagtion information about dataframe and round is used for decimal places

         Age    Salary
count   4.00      4.00
mean   18.75  40000.00
std     3.30  18257.42
min    15.00  20000.00
25%    16.50  27500.00
50%    19.00  40000.00
75%    21.25  52500.00
max    22.00  60000.00

In [7]:
df.to_csv('Test Data.csv' , index=False)

In [8]:
load_df = pd.read_csv('Test Data.csv')
print(load_df)

  Employee  Age  Salary
0     Mosh   21   50000
1     Alex   15   30000
2     Lily   17   20000
3     Eren   22   60000

In [61]:
df[['Age' , 'Salary']] # select rows

   Age  Salary
0   21   50000
1   15   30000
2   17   20000
3   22   60000

In [63]:
df.loc[df.Employee=='Lily']   # select specific rows based on condtion

  Employee  Age  Salary
2     Lily   17   20000

In [70]:
df.iloc[0]                 # selects based on the numeric position of element

Employee     Mosh
Age            21
Salary      50000
Name: 0, dtype: object

In [73]:
df.loc[0:3]                #loc includes the stop value

  Employee  Age  Salary
0     Mosh   21   50000
1     Alex   15   30000
2     Lily   17   20000
3     Eren   22   60000

In [74]:
df.iloc[0:3]              #iloc does not include the stop value

  Employee  Age  Salary
0     Mosh   21   50000
1     Alex   15   30000
2     Lily   17   20000

In [6]:
df[df['Age'] > 15]        #Filtering based on column and condtions

   Name  Age  Salary
0  Mosh   21   50000
2  Lily   17   20000
3  Eren   22   60000

In [7]:
df['Team'] = ['CEO' , 'CTO' , 'HR' , 'DA']  # add new column
df

   Name  Age  Salary Team
0  Mosh   21   50000  CEO
1  Alex   15   30000  CTO
2  Lily   17   20000   HR
3  Eren   22   60000   DA

In [8]:
df['Bonus'] = df['Salary'] * 0.5
df

   Name  Age  Salary Team    Bonus
0  Mosh   21   50000  CEO  25000.0
1  Alex   15   30000  CTO  15000.0
2  Lily   17   20000   HR  10000.0
3  Eren   22   60000   DA  30000.0

In [9]:
df.loc[len(df)] = ['Mikasa' , '21' , 58000 , 'DA' , 30000]
df

     Name Age  Salary Team    Bonus
0    Mosh  21   50000  CEO  25000.0
1    Alex  15   30000  CTO  15000.0
2    Lily  17   20000   HR  10000.0
3    Eren  22   60000   DA  30000.0
4  Mikasa  21   58000   DA  30000.0

In [18]:
len(df)

6

In [13]:
df = df.drop_duplicates()

In [14]:
df.drop('Bonus' , axis=1)   #To drop a column we use axis = 1 , axis = 0  means row , (0,1) = (row,column)

     Name Age  Salary Team
0    Mosh  21   50000  CEO
1    Alex  15   30000  CTO
2    Lily  17   20000   HR
3    Eren  22   60000   DA
4  Mikasa  21   58000   DA

In [23]:
#Sort Value

In [15]:
df.sort_values('Salary')    #Ascending

     Name Age  Salary Team    Bonus
2    Lily  17   20000   HR  10000.0
1    Alex  15   30000  CTO  15000.0
0    Mosh  21   50000  CEO  25000.0
4  Mikasa  21   58000   DA  30000.0
3    Eren  22   60000   DA  30000.0

In [16]:
df.sort_values('Salary' , ascending=False)   #Descending

     Name Age  Salary Team    Bonus
3    Eren  22   60000   DA  30000.0
4  Mikasa  21   58000   DA  30000.0
0    Mosh  21   50000  CEO  25000.0
1    Alex  15   30000  CTO  15000.0
2    Lily  17   20000   HR  10000.0

In [17]:
df

     Name Age  Salary Team    Bonus
0    Mosh  21   50000  CEO  25000.0
1    Alex  15   30000  CTO  15000.0
2    Lily  17   20000   HR  10000.0
3    Eren  22   60000   DA  30000.0
4  Mikasa  21   58000   DA  30000.0

In [19]:
df.isnull()   #Checks for null values

    Name    Age  Salary   Team  Bonus
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False
4  False  False   False  False  False

In [11]:
import numpy as np

In [12]:
df.loc[df.Name == 'Alex' , 'Salary'] = np.nan     #Replaces alex's salary with null value

In [24]:
df

     Name Age   Salary Team    Bonus
0    Mosh  21  50000.0  CEO  25000.0
1    Alex  15      NaN  CTO  15000.0
2    Lily  17  20000.0   HR  10000.0
3    Eren  22  60000.0   DA  30000.0
4  Mikasa  21  58000.0   DA  30000.0

In [26]:
df.isnull()

    Name    Age  Salary   Team  Bonus
0  False  False   False  False  False
1  False  False    True  False  False
2  False  False   False  False  False
3  False  False   False  False  False
4  False  False   False  False  False

In [13]:
df.isnull().sum()   #To check which columns has null values

Employee    0
Age         0
Salary      0
dtype: int64

In [12]:
df.fillna(0)    #To fill the null values

  Employee  Age  Salary
0     Mosh   21   50000
1     Alex   15   30000
2     Lily   17   20000
3     Eren   22   60000

In [13]:
df

     Name Age   Salary Team    Bonus
0    Mosh  21  50000.0  CEO  25000.0
1    Alex  15      NaN  CTO  15000.0
2    Lily  17  20000.0   HR  10000.0
3    Eren  22  60000.0   DA  30000.0
4  Mikasa  21  58000.0   DA  30000.0

In [14]:


data2 = {
    "Order_ID": [101,102,103,104,105,106,107,108,109,110,111,112],
    "Employee": ["Amit","Priya","Amit","Rahul","Priya","Amit","Rahul","Priya","Amit","Rahul","Priya","Amit"],
    "Department": ["Sales","Sales","HR","Sales","HR","Sales","HR","Sales","HR","Sales","HR","Sales"],
    "Product": ["Laptop","Mouse","Keyboard","Laptop","Mouse","Monitor","Keyboard","Laptop","Monitor","Mouse","Laptop","Keyboard"],
    "Region": ["Mumbai","Pune","Mumbai","Delhi","Pune","Mumbai","Delhi","Mumbai","Pune","Delhi","Mumbai","Pune"],
    "Sales": [60000,1500,2500,55000,1800,22000,3000,62000,24000,1700,58000,2800],
    "Quantity": [2,5,3,2,4,1,2,2,1,5,2,3],
    "Rating": [4.5,4.0,4.2,4.8,3.9,4.6,4.1,4.7,4.3,3.8,4.9,4.4]
}

df = pd.DataFrame(data2)

df

    Order_ID Employee Department   Product  Region  Sales  Quantity  Rating
0        101     Amit      Sales    Laptop  Mumbai  60000         2     4.5
1        102    Priya      Sales     Mouse    Pune   1500         5     4.0
2        103     Amit         HR  Keyboard  Mumbai   2500         3     4.2
3        104    Rahul      Sales    Laptop   Delhi  55000         2     4.8
4        105    Priya         HR     Mouse    Pune   1800         4     3.9
5        106     Amit      Sales   Monitor  Mumbai  22000         1     4.6
6        107    Rahul         HR  Keyboard   Delhi   3000         2     4.1
7        108    Priya      Sales    Laptop  Mumbai  62000         2     4.7
8        109     Amit         HR   Monitor    Pune  24000         1     4.3
9        110    Rahul      Sales     Mouse   Delhi   1700         5     3.8
10       111    Priya         HR    Laptop  Mumbai  58000         2     4.9
11       112     Amit      Sales  Keyboard    Pune   2800         3     4.4

In [20]:
df.groupby("Department")["Sales"].agg(["sum", "mean", "min", "max"])

               sum          mean   min    max
Department
HR           89300  17860.000000  1800  58000
Sales       205000  29285.714286  1500  62000